import string as _string

EXTENSIONS = {
    'application/gzip': 'GZ',
    'application/json': 'JSON',
    'application/msword': 'DOC',
    'application/pdf': 'PDF', 'image/tiff': 'TIFF',
    'application/rtf': 'RTF',
    'application/vnd.ms-excel': 'XLS',
    'application/vnd.ms-powerpoint': 'PPT',
    'application/vnd.oasis.opendocument.presentation': 'ODP',
    'application/vnd.oasis.opendocument.spreadsheet': 'ODS',
    'application/vnd.oasis.opendocument.text': 'ODT',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'PPTX',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'XLSX',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'DOCX',
    'application/x-bzip2': 'BZ2',
    'application/x-tar': 'TAR',
    'application/xml': 'XML',
    'application/zip': 'ZIP',
    'audio/mpeg': 'MP3',
    'audio/webm': 'WEBA',
    'font/ttf': 'TTF',
    'font/woff2': 'WOFF2',
    'image/gif': 'GIF',
    'image/jpeg': 'JPG',
    'image/png': 'PNG',
    'image/sgv+xml': 'SVG',
    'image/webp': 'WEBP',
    'image/x-icon': 'ICO',
    'text/css': 'CSS',
    'text/csv': 'CSV',
    'text/html': 'HTML',
    'text/javascript': 'JS',
    'text/plain': 'TXT',
    'video/mp4': 'MP4',
    'video/mpeg': 'MPEG',
    'video/webm': 'WEBM',
}
EXTENSIONS_REVERSE = {value: key for key, value in EXTENSIONS.items()}
FILE_TYPES = {
    'favicons/android-chrome-192x192.png': 'image/png',
    'favicons/android-chrome-512x512.png': 'image/png',
    'favicons/apple-touch-icon.png': 'image/png',
    'favicons/apple-touch-icon-60x60.png': 'image/png',
    'favicons/apple-touch-icon-76x76.png': 'image/png',
    'favicons/apple-touch-icon-120x120.png': 'image/png',
    'favicons/apple-touch-icon-152x152.png': 'image/png',
    'favicons/apple-touch-icon-180x180.png': 'image/png',
    'favicons/browserconfig.xml': 'application/xml',
    'favicons/favicon.ico': 'image/x-icon',
    'favicons/favicon.svg': 'image/svg+xml',
    'favicons/favicon-16x16.png': 'image/png',
    'favicons/favicon-32x32.png': 'image/png',
    'favicons/html_code.html': 'text/html',
    'favicons/mstile-70x70.png': 'image/png',
    'favicons/mstile-144x144.png': 'image/png',
    'favicons/mstile-150x150.png': 'image/png',
    'favicons/mstile-310x150.png': 'image/png',
    'favicons/mstile-310x310.png': 'image/png',
    'favicons/safari-pinned-tab.svg': 'image/svg+xml',
    'favicons/site.webmanifest': 'application/json',
    'fonts/Material-Icons.woff2': 'font/woff2',
    'fonts/Montserrat-Bold.ttf': 'font/ttf',
    'fonts/Montserrat-BoldItalic.ttf': 'font/ttf',
    'fonts/Montserrat-Medium.ttf': 'font/ttf',
    'fonts/Montserrat-MediumItalic.ttf': 'font/ttf',
    'fonts/Roboto.ttf': 'font/ttf',
    'logo.svg': 'image/sgv+xml',
}
GRADES = [
    '-',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
]
LANGUAGES = [
    'de',
    'en',
    'fr',
    'it',
    'es',
    '-'
]
SEARCH_ENGINES = {
    'DuckDuckGo': {
        'url': 'https://duckduckgo.com/?q=%s',
        'recommended': True,
    },
    'BraveSearch': {
        'url': 'https://search.brave.com/search?q=%s',
        'recommended': True,
    },
    'Ecosia': {
        'url': 'https://www.ecosia.org/search?method=index&q=%s',
        'recommended': True,
    },
    'Startpage': {
        'url': 'https://www.startpage.com/sp/search?query=%s',
        'recommended': True,
    },
    'SearXNG': {
        'url': 'https://search.gcomm.ch/search?q=%s&language=de-CH',
        'recommended': True,
    },
    'WolframAlpha': {
        'url': 'https://www.wolframalpha.com/input?i=%s',
        'recommended': True,
    },
    'Google': {
        'url': 'https://www.google.com/search?q=%s',
        'recommended': False,
    },
    'Bing': {
        'url': 'https://www.bing.com/search?q=%s',
        'recommended': False,
    },
    'DuckDuckGo[Lite]': {
        'url': 'https://lite.duckduckgo.com/lite/?q=%s',
        'recommended': True,
    },
    'DuckDuckGo[TOR]': {
        'url': 'https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion/?q=%s',
        'recommended': True,
    },
    'Brave Search[TOR]': {
        'url': 'https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/search?q=%s',
        'recommended': True,
    },
    'SearXNG[TOR]': {
        'url': 'http://searx3aolosaf3urwnhpynlhuokqsgz47si4pzz5hvb7uuzyjncl2tid.onion/search?q=%s', # noqa
        'recommended': True,
    },
}
SIZE_UNITS = [
    'B',
    'KB',
    'MB',
    'GB',
    'TB',
]
SUBJECTS = {
    '-': 'Keines / Anderes',
    'BG': 'Bildnerisches Gestalten',
    'BI': 'Biologie',
    'BL': 'Begleitetes Lernen',
    'CH': 'Chemie',
    'DE': 'Deutsch',
    'EN': 'Englisch',
    'FR': 'Französisch',
    'GG': 'Geografie',
    'GS': 'Geschichte',
    'HW': 'Hauswirtschaft',
    'IN': 'Informatik',
    'KS': 'Klassenstunde',
    'MA': 'Mathematik',
    'MU': 'Musik',
    'NT': 'Natur & Technik',
    'PB': 'Politische Bildung',
    'PH': 'Philosophie',
    'PS': 'Physik',
    'RE': 'Religionskunde & Ethik',
    'SP': 'Sport',
    'TG': 'Technisches Gestalten',
    'WR': 'Wirtschaft & Recht',
    'SAM': 'Schwerpunktfach Anwendungen der Mathematik',
    'SPS': 'Schwerpunktfach Physik',
    'SBI': 'Schwerpunktfach Biologie',
    'SCH': 'Schwerpunktfach Chemie',
    'SBG': 'Schwerpunktfach Bildnerisches Gestalten',
    'SES': 'Schwerpunktfach Spanisch',
    'SIT': 'Schwerpunktfach Italienisch',
    'SMU': 'Schwerpunktfach Musik',
    'SWR': 'Schwerpunktfach Wirtschaft & Recht',
    'EAM': 'Ergänzungsfach Anwendungen der Mathematik',
    'EBG': 'Ergänzungsfach Bildnerisches Gestalten',
    'EBI': 'Ergänzungsfach Biologie',
    'ECH': 'Ergänzungsfach Chemie',
    'EGG': 'Ergänzungsfach Geografie',
    'EGS': 'Ergänzungsfach Geschichte',
    'EIN': 'Ergänzungsfach Informatik',
    'EMU': 'Ergänzungsfach Musik',
    'EPH': 'Ergänzungsfach Philosophie',
    'EPP': 'Ergänzungsfach Pädagogik & Psychologie',
    'EPS': 'Ergänzungsfach Physik',
    'ERE': 'Ergänzungsfach Religionskunde & Ethik',
    'ESP': 'Ergänzungsfach Sport',
    'EWR': 'Ergänzungsfach Wirtschaft & Recht',
    'F': 'Freifach',
}
THEMES = {
    'light': 'Hell',
}
